
print("                      ")
print("                                 WELCOME TO XO11                ")
print("                      ")
print("   ---------------------------------------------------------------------------")
print("  ----------------------------------------------------------------------------- ")
print("                                                            ")
print("            \\\        //  ||````````````||    //||    //|| ")
print("             \\\      //   ||            ||  //  ||  //  || ")
print("              \\\   //     ||            ||      ||      || ")
print("               \\\//       ||            ||      ||      || ")
print("               //\\\       ||            ||      ||      || ")
print("             //   \\\      ||            ||      ||      || ")
print("           //      \\\     ||            ||      ||      || ")
print("         //         \\\    ||,,,,,,,,,,,,||      ||      || ")
print("                                                                 ")
print(" ------------------------------------------------------------------------------- ")
print("   ---------------------------------------------------------------------------")
print("                                                                 ")
import subprocess
print("please enter your interface: eth0 or wlan0 ? ")
interface=input()
print("Enter the mac addresss to change: ")
new_mac = input()

subprocess.run("ifconfig {0} down".format(interface),shell=True)
subprocess.run("ifconfig {0}  hw ether {1}".format(interface,new_mac),shell=True)
subprocess.run("ifconfig {0} up".format(interface),shell=True)
subprocess.run("ifconfig",shell=True)
